#!/bin/bash
# sync-api-keys.sh — Write host API key environment variables into the container's global key file
#
# Runs at container startup to populate /etc/agent-api-keys/global.env
# from two sources, in order:
#   1. Baked-in static config at /etc/agent-api-keys/global.env.static (if present)
#   2. Environment variables injected via docker-compose at runtime
#
# This lets operators choose between:
#   - Baking keys into the image via config/api-keys/global.env
#   - Passing keys at runtime through host environment variables

set -euo pipefail

echo "sync-api-keys: Starting at $(date -Iseconds)"

readonly KEYS_DIR="/etc/agent-api-keys"
readonly LIVE_FILE="${KEYS_DIR}/global.env"
readonly BAKED_FILE="${KEYS_DIR}/global.env.static"

# All credential variable names recognised by the system
readonly RECOGNISED_VARS=(
    "ANTHROPIC_API_KEY"
    "OPENAI_API_KEY"
    "GOOGLE_API_KEY"
    "GEMINI_API_KEY"
    "MISTRAL_API_KEY"
    "COHERE_API_KEY"
    "GROQ_API_KEY"
    "TOGETHER_API_KEY"
    "FIREWORKS_API_KEY"
    "PERPLEXITY_API_KEY"
    "REPLICATE_API_TOKEN"
    "HUGGINGFACE_API_KEY"
    "HF_TOKEN"
    "AWS_ACCESS_KEY_ID"
    "AWS_SECRET_ACCESS_KEY"
    "AWS_DEFAULT_REGION"
    "AZURE_OPENAI_API_KEY"
    "AZURE_OPENAI_ENDPOINT"
    "GITHUB_TOKEN"
    "GH_TOKEN"
)

# Create the keys directory if it isn't already present
echo "sync-api-keys: Ensuring ${KEYS_DIR} exists..."
mkdir -p "$KEYS_DIR"

# Build the output file
echo "sync-api-keys: Writing keys to ${LIVE_FILE}..."
{
    echo "# Global API Keys"
    echo "# Auto-generated by sync-api-keys.sh at $(date -Iseconds)"
    echo "# Do not edit - changes will be overwritten on container restart"
    echo ""

    # Layer 1: baked-in static configuration
    echo "sync-api-keys: Checking for static config at ${BAKED_FILE}..." >&2
    if [[ -f "$BAKED_FILE" ]]; then
        echo "sync-api-keys: Loading static config..." >&2
        echo "# --- From static config ---"
        while IFS='=' read -r k v; do
            [[ "$k" =~ ^[[:space:]]*# ]] && continue
            [[ -z "$k" ]] && continue
            k="$(echo "$k" | xargs)"
            echo "${k}=${v}"
        done < "$BAKED_FILE"
        echo ""
    else
        echo "sync-api-keys: No static config found." >&2
    fi

    # Layer 2: runtime environment variables
    echo "sync-api-keys: Scanning environment for API keys..." >&2
    echo "# --- From environment variables ---"
    for varname in "${RECOGNISED_VARS[@]}"; do
        varval="${!varname:-}"
        if [[ -n "$varval" ]]; then
            echo "${varname}=${varval}"
        fi
    done
} > "$LIVE_FILE"

# Restrict access: readable by the agents group, not world-readable
echo "sync-api-keys: Setting permissions on ${LIVE_FILE}..."
chmod 640 "$LIVE_FILE"
chown root:agents "$LIVE_FILE"

# Report how many credential lines were written
key_count=$(grep -c '^[A-Z]' "$LIVE_FILE" 2>/dev/null || echo "0")
echo "sync-api-keys: Wrote ${key_count} API key(s) to ${LIVE_FILE}"
echo "sync-api-keys: Finished at $(date -Iseconds)"
