#!/bin/bash
# sync-aliases.sh — Rebuild /etc/smtpd/aliases from current agents group membership
#
# Usage: sync-aliases.sh
#
# Steps performed:
#   1. Reads all members of the 'agents' group
#   2. Constructs the 'all' broadcast alias (routes to every agent)
#   3. Constructs per-persona aliases (e.g., coder-all, manager-all)
#   4. Appends any custom entries from /etc/smtpd/aliases.static (if present)
#   5. Atomically overwrites /etc/smtpd/aliases with the result
#
# Invoked automatically by create-agent.sh, remove-agent.sh, agent-manager.sh,
# and soft-reset.sh. Safe to run manually to force a rebuild.

set -euo pipefail

# --- Container check ---
# Proxy execution into the container when called from the host.
# Override the container name via AGENT_HOST_CONTAINER if needed.
if [[ ! -f /.dockerenv ]]; then
    CONTAINER="${AGENT_HOST_CONTAINER:-gaslite}"
    exec docker exec "$CONTAINER" /usr/local/bin/"$(basename "$0")" "$@"
fi

readonly OUTPUT_FILE="/etc/smtpd/aliases"
readonly CUSTOM_FILE="/etc/smtpd/aliases.static"
readonly PERSONA_STORE="/etc/agent-personas"

# Collect the current agent group roster
ROSTER=$(getent group agents 2>/dev/null | cut -d: -f4 | tr ',' ' ')

# Assemble the full aliases file in one pass
{
    echo "# Auto-generated by sync-aliases.sh — do not edit manually"
    echo "# Rebuilt whenever the agent roster changes"
    echo "#"
    echo "# To add custom entries, edit /etc/smtpd/aliases.static"
    echo "# (source: config/smtpd/aliases.static in the repo)"
    echo ""

    # Mandatory system-level aliases
    echo "# System aliases"
    echo "postmaster: root"
    echo ""

    # Broadcast alias: 'all' reaches every registered agent
    if [[ -n "$ROSTER" ]]; then
        BROADCAST=""
        for MEMBER in $ROSTER; do
            if [[ -n "$BROADCAST" ]]; then
                BROADCAST="${BROADCAST}, ${MEMBER}"
            else
                BROADCAST="$MEMBER"
            fi
        done
        echo "# Broadcast alias — reaches every agent"
        echo "all: ${BROADCAST}"
    else
        echo "# Broadcast alias — no agents registered yet"
        echo "# all: (empty — register agents to populate)"
    fi

    # Role-scoped aliases: <persona>-all fans out to every agent with that role
    # A Unix group must exist for a persona before its alias is emitted
    FOUND_PERSONA_ALIASES=false
    if [[ -d "$PERSONA_STORE" ]]; then
        for PFILE in "$PERSONA_STORE"/*.md; do
            [[ -f "$PFILE" ]] || continue
            PNAME=$(basename "$PFILE" .md)
            [[ "$PNAME" == "base" ]] && continue

            # Isolate from errexit: getent exits non-zero when group is absent
            GROUP_MEMBERS=$(getent group "$PNAME" 2>/dev/null | cut -d: -f4 | tr ',' ' ' || true)
            [[ -z "$GROUP_MEMBERS" ]] && continue

            if [[ "$FOUND_PERSONA_ALIASES" == false ]]; then
                echo ""
                echo "# Role aliases — <persona>-all reaches every agent with that role"
                FOUND_PERSONA_ALIASES=true
            fi

            ROLE_LIST=""
            for MEMBER in $GROUP_MEMBERS; do
                if [[ -n "$ROLE_LIST" ]]; then
                    ROLE_LIST="${ROLE_LIST}, ${MEMBER}"
                else
                    ROLE_LIST="$MEMBER"
                fi
            done
            echo "${PNAME}-all: ${ROLE_LIST}"
        done
    fi

    # Append administrator-defined static entries
    if [[ -f "$CUSTOM_FILE" ]]; then
        echo ""
        echo "# Custom aliases (from aliases.static)"
        grep -v '^\s*#' "$CUSTOM_FILE" | grep -v '^\s*$' || true
    fi
} > "$OUTPUT_FILE"

echo "sync-aliases: Updated $OUTPUT_FILE"
if [[ -n "$ROSTER" ]]; then
    echo "sync-aliases: all -> ${ROSTER}"
else
    echo "sync-aliases: No users registered"
fi
